### ISSUE TITLE
Confusion About dlist.h

### ISSUE THREAD

**Issue by karite36** [cisc3130/2-list#10]
I'm lost, for various reasons, not the least of which being that your first TODO in dlist.h has no details (unlike your other ones). I'm not 100% sure what to do. Any guidance or references would be great.

**Comment by TestingYG** [comment]
create a doubly linked list.

**Comment by karite36** [comment]
@TestingYG

Obvious answer is obvious. I'm talking about the TODO in delist with no description.

**Comment by TestingYG** [comment]
fill that part in to start a double linked list.

**Comment by karite36** [comment]
@rivlev
