### ISSUE TITLE
Confusion about Node constructor  with multiple parameters

### ISSUE THREAD

**Issue by FaustinoMalena** [cisc3130/2-list#11]
@rivlev 
Hello professor, i have a quick question is a line of code such as : 

Node* nd = new Node(val, position.nd->prev, position.nd); 

the same as saying : 

nd->next=position.nd;
nd->prev=position.nd->prev;
nd->data=val;

**Comment by rivlev** [comment]
Yes, if you have defined your constructor to take val, prev, and next in that order
