### ISSUE TITLE
Issue with DList Header Node Allocation

### ISSUE THREAD

**Issue by jonesytheartist** [cisc3130/2-list#12]
When running my code through Travis everything runs fine besides this one issue. I'm a bit stumped as this question was previously asked and I removed the * but I still get this error.
@rivlev 

dlist.h:62:19: error: no matching function for call to ‘DList<int>::Node::Node()’
  DList() { head = new Node(); head->next = head; head->prev = head; }
                              ^~~~~~~~~~(should be under new)

**Comment by FaustinoMalena** [comment]
@rivlev 
same for me professor

**Comment by rivlev** [comment]
Did you declare a constructor for node that takes no arguments?

**Comment by jonesytheartist** [comment]
I changed my constructor from:
Node(const T& x, Node* y = NULL, Node* z = NULL) : data(x), prev(y), next(z) {}
to:
Node(const T& x = NULL, Node* y = NULL, Node* z = NULL) : data(x), prev(y), next(z) {}
and it gets rid of the error, just issuing a warning now. It passes through the main.cpp and exits with 0 but it gives me this error and still fails the build.
@rivlev 

In file included from main.cpp:8:0:
dlist.h: In instantiation of ‘DList<T>::DList() [with T = int]’:
main.cpp:36:13:   required from here
dlist.h:62:19: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
  DList() { head = new Node(); head->next = head; head->prev = head; }
                   ^~~~~~~~~~
dlist.h:62:19: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
dlist.h:12:3: note: in passing argument 1 of ‘DList<T>::Node::Node(const T&, DList<T>::Node*, DList<T>::Node*) [with T = int]’
   Node(const T& x = NULL, Node* y = NULL, Node* z = NULL) : data(x), prev(y), next(z) {}  // TODO
   ^~~~
The command "$CXX main.cpp" exited with 0.
0.11s$ ./a.out
/home/travis/.travis/job_stages: line 57:  4113 Segmentation fault      (core dumped) ./a.out
The command "./a.out" exited with 139.

**Comment by fayrouz-mikhael** [comment]
Having the same error

@rivlev

**Comment by fayrouz-mikhael** [comment]
to solve this error :
 DList() : head(new Node(T())){ 	
	 head->next = head;
	 head->prev = head; 
}

Also, you might  get another error after that which is in 
the push_ front 
you have to check the order of the links you made  

I did that and it works 

@rivlev 
@jonesytheartist 
@FaustinoMalena

**Comment by jonesytheartist** [comment]
Thanks for sharing @fayrouz-mikhael ! That fixed my original error and now my program will run with no errors or warnings but I'm still getting the segmentation fault that @FaustinoMalena is getting too. @rivlev 

/home/travis/.travis/job_stages: line 57:  4109 Segmentation fault      (core dumped) ./a.out

**Comment by fayrouz-mikhael** [comment]
yes, this error might be because of the order of the links you made in each function, check that 
I used to have that error

@jonesytheartist
