### ISSUE TITLE
How to Debug a Segmentation fault? 

### ISSUE THREAD

**Issue by TestingYG** [cisc3130/2-list#14]
@rivlev I have went through my code many times and made changes to see if it would fix the segmentation fault but the segmentation fault still persist. How do I check where the segmentation fault is coming from? Xcode just compiles it and everything is fine and Travis is the one that is giving me the fault .

**Comment by rivlev** [comment]
A segmentation fault means that you are dereferencing a null pointer somewhere. Go through everywhere you use the arrow dereferencing operator and make sure that there is no possible way that the node you are trying to access is not null. Make sure that you have allocated a header node in the constructor and that you don't modify that pointer in any of the methods.
