### ISSUE TITLE
unable to activate travis-ci for 2-list

### ISSUE THREAD

**Issue by Presareo** [cisc3130/2-list#17]

**Comment by rivlev** [comment]
I'm not sure why it's not showing up for you, but I can see it on travis and it's activated.
Try pushing a commit and seeing if the check/x shows up

**Comment by jbeece** [comment]
just pulled -> branched -> modified -> pushed 

still not seeing anything happened.

one thing i did notice is that the .travis.yml file for this project is much different than previous projects, could this be causing an issue?

https://github.com/cisc3130/1-vector/blob/master/.travis.yml
https://github.com/cisc3130/2-list/blob/master/.travis.yml


@rivlev
