### ISSUE TITLE
Travis-ci won't activate 2-list repo 

### ISSUE THREAD

**Issue by allina606** [cisc3130/2-list#19]
@rivlev 

I didn't make any changes to the original repo you posed yet. Travis-ci won't let me activate the repo because of the assertion "vec == vec2" failed. 

The command "$CXX main.cpp" exited with 0.
0.11s$ ./a.out
a.out: main.cpp:42: int main(int, char**): Assertion `vec==vec2' failed.
/home/travis/.travis/job_stages: line 57:  4144 Aborted                 (core dumped) ./a.out
The command "./a.out" exited with 134. 

I'm not sure what to do about this, can you help

**Comment by rivlev** [comment]
If you can see the build output in Travis, it is activated.
It looks like you are looking at travis-ci.com/2-list
instead of travis-ci.com/2-list-<YOUR USERNAME>
If you visit that url, you will see a button that says "Activate repository." All you need to do is click it.

**Comment by allina606** [comment]
it says You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.
