### ISSUE TITLE
template parameter error

### ISSUE THREAD

**Issue by Brendafried** [cisc3130/2-list#3]
I am getting this error from the singly linked list file
`./llist.h:6:17: error: declaration of 'T' shadows template parameter
template <class T>`

How do i fix this?
@rivlev

**Comment by rivlev** [comment]
What compiler are you using? It works with gcc and clang. Is this before any changes to the file? @Brendafried

**Comment by Brendafried** [comment]
I am using the gcc compiler. I have already modified the dlist.h file, but did not make any changes to the llist.h file. Would this error have to do with a possible error in my code?
@rivlev

**Comment by rivlev** [comment]
Please sync your code to github so I can take a look @Brendafried

**Comment by rivlev** [comment]
You are missing a close bracket at some point, so your dllist class never ends. @Brendafried
