### ISSUE TITLE
Travis errors! but I can still compile it with no problems

### ISSUE THREAD

**Issue by DullStudent** [cisc3130/2-list#5]
@rivlev 
I have a question, I manage to compile it prefertly on my computer, but when travis does it, there is an error.

![image](https://user-images.githubusercontent.com/31453557/31061336-2afddf60-a6ee-11e7-961e-1dd75e4ff751.png)
![image](https://user-images.githubusercontent.com/31453557/31061357-7868ddae-a6ee-11e7-8254-aabcf7c6e793.png)

**Comment by FaustinoMalena** [comment]
This is the similar for me Professor, by using my own MinGW gcc compiler on my machine my hw 2 seems to work but travis-ci contradicts it

**Comment by rivlev** [comment]
If you look at the screenshot, it is compiling 
```The command "$CXX main.cpp" exited with 0```
but has a runtime error
```Segmentation fault```
```The command "a.out" exited with 139```
@FaustinoMalena @DullStudent

**Comment by FaustinoMalena** [comment]
@rivlev rivlev Hello Professor, I am still having an issue with segmentation fault when running my current version of homework 2 that we previously went over during office hours.

"This is the error I receive
 The command "$CXX main.cpp" exited with 0.
 0.11s$ ./a.out

/home/travis/.travis/job_stages: line 57: 4138 Segmentation fault (core dumped) ./a.out"

I just don't seem to understand where it could be unless what I did for the constructor currently on dList.h isn't correct or perhaps I forgot to do something within the DList functions

just in case I have left a link to my dList.h file just in case:

https://github.com/cisc3130/2-list-FaustinoMalena/blob/hw/dlist.h (url)
