### ISSUE TITLE
CISC 3120 Homework # 2: Segmentation fault persists with modifications to links

### ISSUE THREAD

**Issue by FaustinoMalena** [cisc3130/2-list#6]

**Comment by FaustinoMalena** [comment]
@rivlev 
Hello Professor Levitan, despite recent events i have finally gotten Homework 2 to finally pass it's build but i have made a change to dList.h file. That change specifically was to comment out line 18 of my code which read: Node(const T& x, Node* pnd=NULL, Node* nnd=NULL) : data(x), prev(pnd),next(nnd)  {} 
from within struct Node{} and making the necessary adjustments to every new node in the file . This line however it is a TODO, perhaps i did not know the right syntax when creating a new Node with this three parameter constructor ,i was thinking if you can show me ?

~Faustino Malena

**Comment by rivlev** [comment]
The TODO indicates that you need to modify the node struct to contain a pointer to the previous node, and modify the constructor accordingly. The syntax you used looks correct. The segmentation fault comes from an error in linking up or destroying a new node somewhere.

**Comment by FaustinoMalena** [comment]
so i reverted my code back to its originalsetupafter our last meeting and i get this 
Vdlist.h:76:10: error: no matching function for call to ‘DList<int>::Node::Node()’

   header=new Node();

          ^~~~~~~~~~

dlist.h:18:3: note: candidate: DList<T>::Node::Node(const T&, DList<T>::Node*, DList<T>::Node*) [with T = int]

   Node(const T& x, Node* pnd=NULL, Node* nnd=NULL) : data(x), prev(pnd),next(nnd)  {} // TODO

   ^~~~

dlist.h:18:3: note:   candidate expects 3 arguments, 0 provided

dlist.h:10:9: note: candidate: constexpr DList<int>::Node::Node(const DList<int>::Node&)

  struct Node {

         ^~~~

dlist.h:10:9: note:   candidate expects 1 argument, 0 provided

dlist.h:10:9: note: candidate: constexpr DList<int>::Node::Node(DList<int>::Node&&)

dlist.h:10:9: note:   candidate expects 1 argument, 0 provided

**Comment by FaustinoMalena** [comment]
DList(){ //Doubly Linked List Constructor.

		// TODO: header node should be allocated and linked to itself		
		header= new Node (header->data, header->prev, header); 
		header->prev = header; 
		header->next = header;
		
	}

 
	~DList() { clear(); }//Doubly Linked List Destructor.


	void clear() { while (!empty()) pop_front(); }



	bool empty() { //Check if double link List is empty
		// TODO: with sentinel node, header is never null
		if (header->prev == header){
			return true;
		}else{
			return false;
		}

	}


	void push_front(const T& x) {
		// TODO: with sentinel node, header always stays the same. Links: link header to new first node, new first node to header, new first node to former first node, former first node to new first node.
 		Node* firstnd = new Node(x, header, header->next);

		firstnd->next=header->next;
		header->next->prev=firstnd;
		
		firstnd->prev=header;	
		header->next=firstnd;
		
			
		return;
	}



	void pop_front() {
		// TODO: with sentinel node, header always exists. Links: link header to *second* node, and link second node to header.
		Node* firstnd = header->next;
		
		firstnd->next->prev = header;
		header->next= firstnd->next;
		delete firstnd;	

	}


	void insert(const iterator position, const T& val) {
		// TODO: with sentinel node, header never changes. With prev links, don't need to search list for node before position. Four links.

		Node* nd = new Node(val, position.nd->prev, position.nd);

		nd->next=position.nd;
		position.nd->prev=nd;
		
		nd->prev=position.nd->prev;	
		position.nd->prev->next=nd;
		
		
	}


	void erase(const iterator position) {
		// TODO: fill in
		Node* nd = position.nd;		

		
		nd->next->prev = position.nd->prev;
		position.nd->prev->next= nd->next;
		
		delete nd;
		

	}

**Comment by FaustinoMalena** [comment]
Now i have reverted my program to use the three parameter node constructor again with changes to how i link nodes and i still get a segmentation fault and the linking seems okay to me i need to know if it is really the linking causing the problem?:  
DList(){ //Doubly Linked List Constructor.

		// TODO: header node should be allocated and linked to itself		
		header= new Node (header->data, header->prev, header); 
		header->prev = header; 
		header->next = header;
		
	}

 
	~DList() { clear(); }//Doubly Linked List Destructor.


	void clear() { while (!empty()) pop_front(); }



	bool empty() { //Check if double link List is empty
		// TODO: with sentinel node, header is never null
		if (header->prev == header){
			return true;
		}else{
			return false;
		}

	}


	void push_front(const T& x) {
		// TODO: with sentinel node, header always stays the same. Links: link header to new first node, new first node to header, new first node to former first node, former first node to new first node.
 		Node* firstnd = new Node(x, header, header->next);

		firstnd->next=header->next;
		firstnd->next->prev=firstnd;
		
		firstnd->prev=header;	
		firstnd->prev->next=firstnd;
		
			
		return;
	}



	void pop_front() {
		// TODO: with sentinel node, header always exists. Links: link header to *second* node, and link second node to header.
		Node* firstnd = header->next;
		
		firstnd->next->prev = header;
		firstnd->prev->next= firstnd->next;
		delete firstnd;	

	}


	void insert(const iterator position, const T& val) {
		// TODO: with sentinel node, header never changes. With prev links, don't need to search list for node before position. Four links.

		Node* nd = new Node(val, position.nd->prev, position.nd);

		nd->next=position.nd;
		nd->next->prev=nd;
		
		nd->prev=position.nd->prev;	
		nd->prev->next=nd;
		
		
	}


	void erase(const iterator position) {
		// TODO: fill in
		Node* nd = position.nd;		

		
		nd->next->prev = position.nd->prev;
		nd->prev->next= nd->next;
		
		delete nd;
		

	}



	// TODO: with sentinel node, header is not the first valid node, and null is not one past the last valid node
	iterator begin() {return iterator(header->next);}
	iterator end() {return iterator(header);}



};	// end list


#endif

**Comment by FaustinoMalena** [comment]
@rivlev Hello professor, I have reviewed my code again and immediately rewrote my links for each function and it looks there is still an error with segmentation fault which puzzles me , perhaps there is something  i am still missing here? what could it be? 
~FaustinoMalena
