### ISSUE TITLE
Allocating header node to a Node pointer

### ISSUE THREAD

**Issue by drkitachi** [cisc3130/2-list#7]
@rivlev 
One of the TODO is to allocate the header Node and link it to itself and I am using this code straight from the notes in class:

` Node<T>* header;`
  `list() {
   header = new Node<T>*();
   header->prev = header;
   header->next = header;
  }`

However, it gives me an error that says the following

> error: cannot convert 'DList<int>::Node**' to 'DList<int>::Node*' in assignment|

I am wondering if it is actually legal to do header = new Node<T>*() 
Allocating a pointer to a pointer?

This is my code:

`DList() {
	head = new Node*();
        head->next = head;
        head->prev = head;
	}`

**Comment by rivlev** [comment]
Yes, the asterisk should be removed
```head = new Node();```
