### ISSUE TITLE
Unknown Assertion Failure

### ISSUE THREAD

**Issue by tovabaharlias** [cisc3130/2-list#8]
@rivlev 
I keep getting this assertion failure:
Assertion failed: (vec==vec2), function main, file /Users/tovabaharlias/CISC/2-list-tovabaharlias/main.cpp, line 42.
Abort trap: 6

I'm not sure exactly what's causing it

**Comment by rivlev** [comment]
This assertion tests selection sort
your selectionSort is called on vec
std::sort is called on vec2
and this assertion tests that after both sorts both vectors are the same.
If they aren't, your selectionSort isn't working correctly
