### ISSUE TITLE
Error on Line 50. Main.cpp 

### ISSUE THREAD

**Issue by TestingYG** [cisc3130/2-list#9]
@rivlev, Im getting a Error, on Line 50 on Main.CPP, I can't pinpoint where the error is in my Dlist.h file. Can i get some pointers where the error is?  

![screen shot 2017-10-09 at 10 14 41 am](https://user-images.githubusercontent.com/31413025/31344491-dd706648-ace0-11e7-83c8-a370276b86b7.png)

**Comment by rivlev** [comment]
If the first assertion passed, your implementation of selection sort is correct
so something must be wrong with your dlist implementation.

In push_front, you set head to nd. The sentinel node never changes, so you should never be modifying head -- it should always be pointing to the original sentinel node you allocated in the constructor.
